import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-4xl">
          Joshua&apos;s Books: <Link href="/books-joshua">Click me!</Link>
        </h1>
        <h1 className="text-4xl">
          Leo&apos;s Books: <Link href="/books-leo">Click me!</Link>
        </h1>
      </main>
    </div>
  )
}
