import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-4xl">
<<<<<<< HEAD
          Welcome to my house<a href="/sub-page">Next.js!</a>
=======
          Joshua's Books: <a href="/books-joshua">Click me!</a>
        </h1>
        <h1 className="text-4xl">
          Leo's Books: <a href="/books-leo">Click me!</a>
>>>>>>> 2d20803ddde22e683bcb895ed37c8e90c8f370e0
        </h1>
      </main>
    </div>
  )
}
