import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-4xl">
          Joshua's Books: <a href="/books-joshua">Click me!</a>
        </h1>
        <h1 className="text-4xl">
          Leo's Books: <a href="/books-leo">Click me!</a>
        </h1>
      </main>
    </div>
  )
}
